from __future__ import annotations

import json

import pandas as pd
import pytest

from conftest import ARTIFACTS_READY, LAKE_DIR, MODELS_DIR
from harm_detection.config import REQUIRED_SILVER_COLUMNS


# Global test marker assigning this entire module to the 'artifacts' integration suite.
# These integration tests validate physical output files generated by the ETL and training pipelines.
pytestmark = pytest.mark.artifacts


def _expected_final_model(summary: dict[str, object]) -> tuple[str, str, bool]:
    """
    Helper Function: Model Selection Decision Tree Emulator
    ---------------------------------------------------------
    Replicates the automated production decision tree for model selection to cross-verify 
    that the saved training summary JSON picked the absolute best candidate configuration.

    Selection Workflow:
    1. Candidate Evaluation: Compares 'Expert + Weak' against 'Expert + Weak + Pseudo'.
       Accepts Pseudo labels ONLY if they bring in rows AND do not degrade Macro F1 or Recall.
    2. Final Step: Compares the chosen augmented model against the baseline 'Expert Only'.
       Promotes the augmented model if it beats the baseline on Macro F1, or matches Macro F1 
       while improving/maintaining Recall.
    """
    validation_metrics = summary["validation_metrics"]
    baseline_val = validation_metrics["expert_only"]
    weak_val = validation_metrics["expert_plus_weak"]
    pseudo_val = validation_metrics["expert_plus_weak_plus_pseudo"]
    pseudo_summary = summary["pseudo_label_summary"]

    selected_augmented_name = "expert_plus_weak"
    pseudo_kept = False
    if pseudo_summary["accepted_rows"] > 0 and (
        pseudo_val["macro_f1"] >= weak_val["macro_f1"] and pseudo_val["recall"] >= weak_val["recall"]
    ):
        selected_augmented_name = "expert_plus_weak_plus_pseudo"
        pseudo_kept = True

    selected_val = weak_val if selected_augmented_name == "expert_plus_weak" else pseudo_val
    final_name = "expert_only"
    if (
        selected_val["macro_f1"] > baseline_val["macro_f1"]
        or (
            selected_val["macro_f1"] == baseline_val["macro_f1"]
            and selected_val["recall"] >= baseline_val["recall"]
        )
    ):
        final_name = selected_augmented_name
    return final_name, selected_augmented_name, pseudo_kept


@pytest.mark.skipif(not ARTIFACTS_READY, reason="Generated artifacts are required for this test.")
def test_bronze_manifest_matches_local_source_profile() -> None:
    """
    Test Component: Bronze Layer Manifest & Ingestion Integrity
    -----------------------------------------------------------
    Validates the raw data lake entry point (Bronze Layer).
    - Verifies raw ingestion row counts and structural flaws (e.g., blank videos) across 
      all multi-source inputs (Expert annotations, GPT-4 LLM labels, Crowdworkers, Unlabeled pool).
    - Audits the dirty-data cleanup process for the raw massive unlabeled pool, ensuring that 
      exactly 816 null bytes and 1,783 malformed lines were successfully intercepted and dropped.
    """
    manifest = json.loads((LAKE_DIR / "bronze" / "_manifest.json").read_text(encoding="utf-8"))
    expected = {
        "agreement_full_harmful": {"row_count": 5901, "blank_video_rows": 0},
        "agreement_subset_harmful": {"row_count": 14019, "blank_video_rows": 39},
        "domain_expert_harmful": {"row_count": 15114, "blank_video_rows": 57},
        "domain_expert_harmless": {"row_count": 3302, "blank_video_rows": 8},
        "gpt4_turbo_harmful": {"row_count": 10494, "blank_video_rows": 0},
        "gpt4_turbo_harmless": {"row_count": 7818, "blank_video_rows": 24},
        "crowdworker_harmful": {"row_count": 12668, "blank_video_rows": 46},
        "crowdworker_harmless": {"row_count": 4390, "blank_video_rows": 16},
        "crowdworker_harmless_duplicate": {"row_count": 4390, "blank_video_rows": 16},
        "unlabeled_large_pool": {"row_count": 60905, "blank_video_rows": 1},
    }
    observed = {item["source_name"]: item for item in manifest["sources"]}
    for source_name, counts in expected.items():
        assert observed[source_name]["row_count"] == counts["row_count"]
        assert observed[source_name]["blank_video_rows"] == counts["blank_video_rows"]

    unlabeled = observed["unlabeled_large_pool"]
    assert unlabeled["nul_bytes_removed"] == 816
    assert unlabeled["malformed_lines"] == 1783


@pytest.mark.skipif(not ARTIFACTS_READY, reason="Generated artifacts are required for this test.")
def test_silver_contract_and_unlabeled_dedup_audit() -> None:
    """
    Test Component: Silver Layer Data Contract & Deduplication
    ----------------------------------------------------------
    Validates data cleaning, normalization, and structural contracts (Silver Layer).
    - Structural Contract: Enforces that all required downstream columns are present and that 
      no records contain missing unique 'video_id' keys.
    - Deduplication Audit: Confirms that known duplicate tracking sources (e.g., crowdworker clones) 
      were completely purged.
    - Data Quality Check: Assures string manipulations successfully restored text data and caught 
      unlabeled video IDs, dropping the raw pool down to a unique cardinality of exactly 59,671 records.
    """
    silver = pd.read_parquet(LAKE_DIR / "silver" / "records.parquet")
    assert set(REQUIRED_SILVER_COLUMNS).issubset(silver.columns)
    assert silver["video_id"].isna().sum() == 0
    assert "crowdworker_harmless_duplicate" not in set(silver["source_name"])
    unlabeled = silver.loc[silver["source_name"] == "unlabeled_large_pool"]
    assert int(unlabeled["text_present"].sum()) > 0

    bronze_unlabeled = pd.read_parquet(LAKE_DIR / "bronze" / "unlabeled_large_pool.parquet", columns=["video_id"])
    unique_unlabeled = (
        bronze_unlabeled["video_id"]
        .dropna()
        .astype(str)
        .str.strip()
        .replace("", pd.NA)
        .dropna()
        .nunique()
    )
    assert unique_unlabeled == 59671


@pytest.mark.skipif(not ARTIFACTS_READY, reason="Generated artifacts are required for this test.")
def test_gold_splits_are_disjoint_and_fixed() -> None:
    """
    Test Component: Gold Layer ML Data Splits Verification
    -----------------------------------------------------
    Protects the Machine Learning training foundation inside the curated Gold Layer.
    - Strict Isolation: Asserts that Train, Validation, and Test datasets are completely 
      disjoint sets (zero overlapping video IDs) to guarantee no data leakage occurs.
    - Deterministic Balance: Enforces an exact, immutable distribution of data splits 
      (12,844 Train / 2,752 Validation / 2,753 Test) to guarantee experimental reproducibility.
    """
    splits = pd.read_parquet(LAKE_DIR / "gold" / "splits.parquet")
    train_ids = set(splits.loc[splits["split"] == "train", "video_id"])
    validation_ids = set(splits.loc[splits["split"] == "validation", "video_id"])
    test_ids = set(splits.loc[splits["split"] == "test", "video_id"])

    assert train_ids.isdisjoint(validation_ids)
    assert train_ids.isdisjoint(test_ids)
    assert validation_ids.isdisjoint(test_ids)
    assert len(splits) == 18349
    assert splits["split"].value_counts().to_dict() == {
        "train": 12844,
        "test": 2753,
        "validation": 2752,
    }


@pytest.mark.skipif(not ARTIFACTS_READY, reason="Generated artifacts are required for this test.")
def test_training_summary_follows_selection_rules_and_records_pseudo_funnel() -> None:
    """
    Test Component: Weak Supervision & Pseudo-Labeling Selection Funnel
    --------------------------------------------------------------------
    Validates the optimization engine of the system's training logic.
    - Decision Integrity: Cross-checks the summary metadata against the '_expected_final_model' 
      decision tree to ensure the production pipeline didn't deploy a suboptimal model configuration.
    - Funnel Progression: Enforces a mathematical cascade on the self-training pseudo-label funnel:
      Total Text Rows >= Post-Holdout Filtering >= Candidates >= Final Accepted Rows.
    """
    summary = json.loads((MODELS_DIR / "training_summary.json").read_text(encoding="utf-8"))
    expected_final, expected_augmented, expected_pseudo_kept = _expected_final_model(summary)
    assert summary["final_model_name"] == expected_final
    assert summary["selected_augmented_model"] == expected_augmented
    assert summary["pseudo_label_summary"]["kept_for_final_model"] is expected_pseudo_kept
    assert summary["weak_label_summary"]["accepted_rows"] > 0

    pseudo = summary["pseudo_label_summary"]
    assert pseudo["with_any_text_rows"] >= pseudo["after_holdout_rows"] >= pseudo["candidate_rows"] >= pseudo["accepted_rows"]
    if pseudo["kept_for_final_model"]:
        assert pseudo["accepted_rows"] > 0
    else:
        assert pseudo["accepted_rows"] >= 0


@pytest.mark.skipif(not ARTIFACTS_READY, reason="Generated artifacts are required for this test.")
def test_accepted_weak_and_pseudo_labels_do_not_leak_into_holdouts() -> None:
    """
    Test Component: ML Leakage Firewall Audit
    -----------------------------------------
    A critical safety check guarding against data leakage from weak supervision sources.
    - Leakage Prevention: Extracts the evaluation/test IDs (Holdout set) and aggressively 
      asserts that absolutely zero weak labels or pseudo-labeled videos from the unlabeled 
      pool bled back into the Validation or Test populations.
    - Integrity Value: Prevents artificial inflation of performance metrics during validation sweeps.
    """
    splits = pd.read_parquet(LAKE_DIR / "gold" / "splits.parquet")
    holdout_ids = set(splits.loc[splits["split"].isin(["validation", "test"]), "video_id"])
    summary = json.loads((MODELS_DIR / "training_summary.json").read_text(encoding="utf-8"))

    weak_labels = pd.read_csv(summary["weak_label_summary"]["accepted_labels_path"])
    assert set(weak_labels["video_id"]).isdisjoint(holdout_ids)

    pseudo_labels = pd.read_csv(summary["pseudo_label_summary"]["accepted_labels_path"])
    if not pseudo_labels.empty:
        assert set(pseudo_labels["video_id"]).isdisjoint(holdout_ids)


@pytest.mark.skipif(not ARTIFACTS_READY, reason="Generated artifacts are required for this test.")
def test_data_quality_summary_includes_source_text_coverage() -> None:
    """
    Test Component: Feature Denseness & Text Coverage Profile
    ----------------------------------------------------------
    Monitors data health metrics across critical metadata fields.
    - Coverage Audit: Scans the gold quality summary to verify that text fields (Titles, 
      Descriptions, and Transcripts) are populated with feature data.
    - Downstream Protection: Ensures downstream multi-modal transformer/NLP models won't encounter 
      completely hollow feature vectors during training.
    """
    summary = json.loads((LAKE_DIR / "gold" / "data_quality_summary.json").read_text(encoding="utf-8"))
    unlabeled_coverage = summary["source_text_coverage"]["unlabeled_large_pool"]
    assert unlabeled_coverage["text_present_count"] > 0
    assert unlabeled_coverage["title_present_count"] > 0
    assert unlabeled_coverage["description_present_count"] > 0
    assert unlabeled_coverage["transcript_present_count"] > 0
    assert summary["wide_text_coverage"]["text_present_count"] > 0


@pytest.mark.skipif(not ARTIFACTS_READY, reason="Generated artifacts are required for this test.")
def test_validation_threshold_sweep_artifact_is_present_and_complete() -> None:
    """
    Test Component: Decision Boundary Validation Sweep
    --------------------------------------------------
    Audits the hyperparameter metrics configuration file.
    - Matrix Completeness: Checks that threshold metrics exist for all three model frameworks 
      (Expert, Expert+Weak, Expert+Weak+Pseudo).
    - Granularity Check: Validates that inference probability thresholds were swept comprehensively 
      from 5% to 95% in step increments of 5%.
    - Range Invariance: Mathematically confirms that every single recorded evaluation metric 
      (Macro F1, Precision, Recall) stays bounded within valid mathematical limits [0.0, 1.0].
    """
    summary = json.loads((MODELS_DIR / "training_summary.json").read_text(encoding="utf-8"))
    threshold_sweep = pd.read_csv(summary["validation_threshold_sweep_path"])
    assert set(threshold_sweep["model_name"]) == {
        "expert_only",
        "expert_plus_weak",
        "expert_plus_weak_plus_pseudo",
    }
    assert set(threshold_sweep["threshold"]) == {step / 100 for step in range(5, 100, 5)}
    assert threshold_sweep["macro_f1"].between(0.0, 1.0).all()
    assert threshold_sweep["precision"].between(0.0, 1.0).all()
    assert threshold_sweep["recall"].between(0.0, 1.0).all()


@pytest.mark.skipif(not ARTIFACTS_READY, reason="Generated artifacts are required for this test.")
def test_canonical_merge_audit_records_selected_sources() -> None:
    """
    Test Component: Multi-Source Canonical Truth Merge Audit
    --------------------------------------------------------
    Validates data provenance and the system's "source of truth" resolution engine.
    - Provenance Mapping: Ensures the Gold layer tracks exactly which source won the metadata 
      conflict resolution for titles, descriptions, transcripts, and publish dates.
    - Redundancy Check: Confirms that only records originating from overlapping sources 
      (at least 2 matching references) were processed into this canonical master map.
    """
    audit = pd.read_parquet(LAKE_DIR / "gold" / "audit_canonical_merges.parquet")
    assert not audit.empty
    expected_columns = {
        "video_id",
        "canonical_title_source",
        "canonical_description_source",
        "canonical_transcript_source",
        "canonical_published_date_source",
    }
    assert expected_columns.issubset(set(audit.columns))
    assert audit["record_count"].ge(2).all()
